notifications:
  email: false

language: c
sudo: true

branches:
  only:
  - master
  - travis
  
compiler:
  - gcc
  - touch ~/gcc-5; gcc-5
  - touch ~/gcc-7; gcc-7
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    - gcc-5
    - gcc-7
    - bear
    - clang-tidy-5.0

before_install:
  - chmod +x ./run.sh
  - if [ -f ~/gcc-5 ] ; then export CC=gcc-5; fi
  - if [ -f ~/gcc-7 ] ; then export CC=gcc-7; fi

install:
  - sudo sysctl kernel.yama.ptrace_scope=0
  - pip install --user numpy
  - wget -q ${SDE_URL}
  - tar xvf ${SDE_ARCHIVE}.tar.bz2
  - export PATH=${PATH}:${TRAVIS_BUILD_DIR}/${SDE_ARCHIVE}

script:
  - ./run.sh
