notifications:
  email: false

language: cpp
sudo: false

branches:
  only:
  - master
  - travis
  
compiler:
  - gcc

before_install:
  - chmod +x aestest/run.sh

install:
  - git submodule init
  - git submodule update

script:
  - cd $TRAVIS_BUILD_DIR/aestest
  - ./run.sh -p
  - cd $TRAVIS_BUILD_DIR/Putty
  - ./mkfiles.pl
  - cd unix
  - ./configure
  - make
