notifications:
  email: false

language: c
dist: bionic
  
compiler:
  - gcc
  - clang

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - python3

script:
  - make aescpuid
  - ./aescpuid
  - make sshaes-demo-sw-encode sshaes-demo-hw-encode sshaes-demo-sw-decode sshaes-demo-hw-decode
  - make perf-geomean-aes.txt
  - echo "Speedup in geomean is:" && cat perf-geomean-aes.txt
