notifications:
  email: false

language: cpp
sudo: false

branches:
  only:
  - master
  - travis
  
compiler:
  - gcc
  - clang

before_install:
  - chmod +x aestest/run.sh

install:
  - git submodule init
  - git submodule update
  - pip install --user numpy

script:
  - cd $TRAVIS_BUILD_DIR/aestest
  - ./run.sh
  - ./run.sh -p
  - cd $TRAVIS_BUILD_DIR/Putty
  - ./mkfiles.pl -U
  - make pscp
