notifications:
  email: false

language: cpp
sudo: false

branches:
  only:
  - master
  - travis
  
compiler:
  - gcc
  - touch ~/gcc-5; gcc-5
  - touch ~/gcc-7; gcc-7
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - gcc-7

before_install:
  - chmod +x aestest/run.sh
  - if [ -f ~/gcc-5 ] ; then export CC=gcc-5; fi
  - if [ -f ~/gcc-7 ] ; then export CC=gcc-7; fi

install:
  - pip install --user numpy
  - wget -q ${SDE_URL}
  - tar xvf ${SDE_ARCHIVE}.tar.bz2
  - mv ${SDE_ARCHIVE} sde
  - export PATH=$PATH:${TRAVIS_BUILD_DIR}/sde
  - export VPATH=$VPATH:${TRAVIS_BUILD_DIR}/sde

script:
  - cd $TRAVIS_BUILD_DIR/aestest
  - ./run.sh
  - ./run.sh -p
  - cd $TRAVIS_BUILD_DIR/Putty
  - ./mkfiles.pl -U
  - make pscp
