version: "{branch}-ci-{build}"
image: Visual Studio 2015

branches:
  only:
  - master

platform:
  - x86
  - x64
# - arm
# - arm64

environment:
  matrix:
  - build: msvc
  - build: clang
  - build: gcc
    
before_build:
- git submodule update --init
- if "%platform%"=="arm" (call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_arm) else (call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %platform%)
- set PATH=%PATH%;C:\Perl;C:\Program Files\LLVM\bin;C:\MinGW\bin;
# For LLVM-RC binary
- set PATH=%PATH%;C:\projects\putty-aes-ni
- set platform=%platform%

build_script:
- cd C:\projects\putty-aes-ni\Putty
- perl ./mkfiles.pl
- cd windows
# Copy MinGW WinAPI headers
- if "%build%"=="gcc" copy C:\msys64\usr\include\w32api\htmlhelp.h .
- if "%build%"=="gcc" copy C:\msys64\usr\include\w32api\_mingw_unicode.h .
- if "%build%"=="gcc" copy C:\msys64\usr\include\w32api\multimon.h .
- if "%build%"=="gcc" copy C:\msys64\usr\include\w32api\winapifamily.h .
# Build
- if "%build%"=="msvc" nmake -f Makefile.vc
- if "%build%"=="clang" mingw32-make -f Makefile.clangcl Platform="%Platform%"
- if "%build%"=="gcc" mingw32-make -f Makefile.mgw Platform="%Platform%"

test_script:
- cd C:\projects\putty-aes-ni\Putty\windows
- dir *.exe
