version: "{branch}-ci-{build}"
image: Visual Studio 2013

branches:
  only:
  - master
  - appveyor
  
environment:
  matrix:
  - build: msvc
    platform: x86
  - build: msvc
    platform: x64
#  - build: g++
#    platform: x86
#    CYGWIN_ROOT: C:\cygwin
#  - build: g++
#    platform: x64
#    CYGWIN_ROOT: C:\cygwin64
    
before_build:
- cmd: git submodule update --init
- cmd: if "%build%"=="msvc" call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
- cmd: set PATH=%PATH%;C:\Perl
- cmd: if not "%build%"=="msvc" set PATH=%CYGWIN_ROOT%;%CYGWIN_ROOT%\bin;%PATH%

build_script:
- cmd: cd C:\projects\putty-aes-ni\Putty
- cmd: perl ./mkfiles.pl
- cmd: cd windows
- cmd: if "%build%"=="msvc" nmake -f Makefile.vc
- cmd: if not "%build%"=="msvc" bash -lc "cd /cygdrive/c/projects/putty-aes-ni/Putty/windows; make -f Makefile.mgw"

test_script:
- cmd: cd C:\projects\putty-aes-ni\Putty\windows
- cmd: dir *.exe
