version: "{branch}-ci-{build}"
image: Visual Studio 2015

branches:
  only:
  - master
  
environment:
  matrix:
  - build: msvc
    platform: x64
  - build: msvc
    platform: x86
#  - build: clang
#    platform: x86
 # - build: gcc
 #   platform: x86
    
before_build:
- git submodule update --init
- call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
- set PATH=%PATH%;C:\Perl;C:\Program Files\LLVM\bin;C:\MinGW\bin

build_script:
- cd C:\projects\putty-aes-ni\Putty
- perl ./mkfiles.pl
- cd windows
- if "%build%"=="msvc" nmake -f Makefile.vc
- if "%build%"=="clang" mingw32-make -f Makefile.clangcl
- if "%build%"=="gcc" mingw32-make -f Makefile.mgw

test_script:
- cd C:\projects\putty-aes-ni\Putty\windows
- dir *.exe
