version: "{branch}-ci-{build}"
image: Visual Studio 2013

branches:
  only:
  - master
  - appveyor
  
environment:
  matrix:
  - build: msvc
    platform: x86
  - build: msvc
    platform: x64
  - build: clang
    platform: x86
  - build: clang
    platform: x64
    
before_build:
- cmd: git submodule update --init
- cmd: if "%build%"=="msvc" call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
- cmd: set PATH=%PATH%;C:\Perl;C:\Program Files\LLVM\bin
- cmd: if "%build%"=="gcc" set PATH=%CYGWIN_ROOT%;%CYGWIN_ROOT%\bin;%PATH%

build_script:
- cmd: cd C:\projects\putty-aes-ni\Putty
- cmd: perl ./mkfiles.pl
- cmd: cd windows
- cmd: if "%build%"=="msvc" nmake -f Makefile.vc
- cmd: if "%build%"=="clang" C:\MinGW\bin\make -f Makefile.clangcl
- cmd: if "%build%"=="gcc" C:\msys64\usr\bin\bash -lc "cd /c/projects/putty-aes-ni/Putty/windows; make -f Makefile.mgw"

test_script:
- cmd: cd C:\projects\putty-aes-ni\Putty\windows
- cmd: dir *.exe
