version: "{branch}-ci-{build}"
image: Visual Studio 2015

branches:
  only:
  - master
  
environment:
  matrix:
  - build: msvc
    platform: x64
  - build: msvc
    platform: x86
  - build: clang
    platform: x86
 # - build: gcc
 #   platform: x86
    
before_build:
- cmd: git submodule update --init
- cmd: call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
- cmd: set PATH=%PATH%;C:\Perl;C:\Program Files\LLVM\bin;C:\MinGW\bin

build_script:
- cmd: cd C:\projects\putty-aes-ni\Putty
- cmd: perl ./mkfiles.pl
- cmd: cd windows
- cmd: copy C:\MinGW\bin\windres.exe C:\MinGW\bin\i686-w64-mingw32-windres.exe
- cmd: if "%build%"=="msvc" nmake -f Makefile.vc
- cmd: if "%build%"=="clang" mingw32-make -f Makefile.clangcl
- cmd: if "%build%"=="gcc" mingw32-make -f Makefile.mgw

test_script:
- cmd: cd C:\projects\putty-aes-ni\Putty\windows
- cmd: dir *.exe
