version: "{branch}-ci-{build}"
image: Visual Studio 2013

branches:
  only:
  - master
  - appveyor
  
environment:
  matrix:
  - build: msvc
    platform: x86
  - build: msvc
    platform: x64
  - build: g++
    platform: x86
    MINGW_ROOT: C:\msys64\mingw32
  - build: g++
    platform: x64
    MINGW_ROOT: C:\msys64\mingw64
    
before_build:
- cmd: git submodule init
- cmd: git submodule update
- cmd: if "%build%"=="msvc" call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
- cmd: set PATH=%PATH%;C:\Perl
- cmd: if not "%build%"=="msvc" set PATH=%MINGW_ROOT%;%MINGW_ROOT%\bin;C:\msys64\usr\bin\;%PATH%

build_script:
- cmd: cd C:\projects\putty-aes-ni\Putty
- cmd: if "%build%"=="msvc" perl ./mkfiles.pl
- cmd: if not "%build%"=="msvc" bash -lc "cd /c/projects/putty-aes-ni/Putty; perl ./mkfiles.pl"
- cmd: cd windows
- cmd: if "%build%"=="msvc" nmake -f Makefile.vc
- cmd: if not "%build%"=="msvc" bash -lc "cd /c/projects/putty-aes-ni/Putty/windows; make -f Makefile.mgw"

test_script:
- cmd: cd C:\projects\putty-aes-ni\Putty\windows
- cmd: dir *.exe
