version: "{branch}-ci-{build}"
image: Visual Studio 2015

branches:
  only:
  - master

platform:
  - x86
  - x64
  - arm

environment:
  matrix:
  - build: msvc
  - build: clang
  - build: gcc
  
matrix:
  exclude:
    - build: gcc
      platform: arm

before_build:
- git submodule update --init
- if "%platform%"=="arm" (call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_arm) else (call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %platform%)
- set PATH=%PATH%;C:\Perl;C:\Program Files\LLVM\bin;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;
# For LLVM-RC binary
- set PATH=%PATH%;C:\projects\putty-aes-ni
# Convert to lowercase
- if "%platform%"=="X64" set platform=x64
- if "%platform%"=="ARM" set platform=arm

build_script:
- cd C:\projects\putty-aes-ni\Putty
- perl ./mkfiles.pl
- cd windows
# Build
- if "%build%"=="msvc" nmake -f Makefile.vc
- if "%build%"=="clang" C:\MinGW\bin\mingw32-make -f Makefile.clangcl Platform="%Platform%"
- if "%build%"=="gcc" C:\MinGW\bin\mingw32-make -f Makefile.mgw Platform="%Platform%"

test_script:
- cd C:\projects\putty-aes-ni\Putty\windows
- dir *.exe
