name: AES Performance Measurement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Benchmark
      run: sudo apt-get install libbenchmark-dev
 
    - name: Run CMake
      run: cmake .
   
    - name: Build tools
      run: make all
      
    - name: Check CPUID
      run: ./aescpuid

    - name: Measure performance
      run: ./aesperf | grep BigO
