name: AES Performance Measurement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      working-directory: build
      run: cmake ..
   
    - name: Build tools
      working-directory: build
      run: make all
      
    - name: Check CPUID
      working-directory: build
      run: ./aescpuid

    - name: Measure performance
      run: make perf-geomean-aes.txt

    - name: Show performance
      run: echo "Speedup in geomean is:" && cat perf-geomean-aes.txt
